port: 7890
socks-port: 7891
tproxy-port: 7893
ipv6: false
allow-lan: true
bind-address: '*'
mode: rule
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
geo-auto-update: false
geo-update-interval: 24
log-level: info
external-controller: '0.0.0.0:9090'
unified-delay: true
secret: ''
experimental:
    ignore-resolve-fail: true
cfw-latency-timeout: 8000
cfw-latency-url: 'http://YouTube.com/generate_204'
cfw-conn-break-strategy: true
external-ui: '/opt/mihomo/ui/'
external-ui-name: 'xd'
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
routing-mark: 2158
sniffer:
  enable: true
  parse-pure-ip: true
profile:
  store-selected: true
  store-fake-ip: true
hosts:
    mtalk.google.com: 108.177.125.188
    services.googleapis.cn: 74.125.203.94
dns:
    enable: true
    listen: '0.0.0.0:7874'
    ipv6: false
    default-nameserver: [119.6.6.6, 223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    fake-ip-filter: [+.lan, +.cn, +.10010.com, +.chinaunicom.com, '*.alipay.com', '*.alipayobjects.com', connect.rom.miui.com, localhost.ptlogin2.qq.com, '+.stun.*.*', '+.stun.*.*.*', '+.stun.*.*.*.*', '+.stun.*.*.*.*.*', '*.n.n.srv.nintendo.net', +.stun.playstation.net, '*.msftncsi.com', '*.msftconnecttest.com', ntp.ntsc.ac.cn, controlplane.tailscale.com, log.tailscale.io]
    nameserver: ['https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']
    fallback: ['tls://8.8.4.4', 'https://dns.twnic.tw/dns-query']
    fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
