mixed-port: 7890
ipv6: false
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
unified-delay: true
secret: ''
experimental:
    ignore-resolve-fail: true
cfw-latency-timeout: 8000
cfw-latency-url: 'http://YouTube.com/generate_204'
cfw-conn-break-strategy: true
hosts:
    mtalk.google.com: 108.177.125.188
    services.googleapis.cn: 74.125.203.94
dns:
    enable: true
    listen: '127.0.0.1:53'
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 28.0.0.1/8
    use-hosts: true
    fake-ip-filter: [+.lan, +.cn, +.10010.com, +.chinaunicom.com, '*.alipay.com', '*.alipayobjects.com', connect.rom.miui.com, localhost.ptlogin2.qq.com, '+.stun.*.*', '+.stun.*.*.*', '+.stun.*.*.*.*', '+.stun.*.*.*.*.*', '*.n.n.srv.nintendo.net', +.stun.playstation.net, '*.msftncsi.com', '*.msftconnecttest.com', ntp.ntsc.ac.cn]
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['tls://8.8.4.4', 'https://dns.twnic.tw/dns-query']
    fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
